alias rm='rm -i'
alias hdfsl='hdfs dfs -ls'
alias hdfsd='hdfs dfs -du -h'
alias hdfsds='hdfs dfs -du -h -s'
alias hdfsg='hdfs dfs -get'
alias hdfsp='hdfs dfs -put'
alias hdfsm='hdfs dfs -mv'
alias hdfsmk='hdfs dfs -mkdir'
alias hdfsr='hdfs dfs -rm -r'
alias hdfsrs='hdfs dfs -rm -r -skipTrash'
alias hdfsc='hdfs dfs -cat'
alias hdfscp='hdfs dfs -cp'
alias hdfsch='hdfs dfs -chmod -R 777'
alias yarnk='yarn application -kill'
alias duh='du -h --max-depth=1'
cd /data/houcunyue/adcpi/run/bin
